# Generated by Django 3.1.6 on 2021-07-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_on',
        ),
    ]
